version: '3.9'

services:
  java-app:
    build:
      context: . # Ubicación del Dockerfile en el directorio actual
      dockerfile: Dockerfile
    image: helloworld-app # Nombre de la imagen Docker
    ports:
      - '8081:8080' # Puerto 8081 del host mapeado al puerto 8080 del contenedor
    restart: always # Reinicia automáticamente si el contenedor falla
